name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
        matrix:
          os: [windows-latest]
          
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '3.10'
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

        
    - name: Install Windows Dependencies
      if: ${{matrix.os}} == 'windows-latest'
      run: |
        python -m venv venv
        ./venv/Scripts/activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        deactivate

    - name: Install Linux Dependencies
      if: ${{matrix.os}} == 'ubuntu-latest'
      run: |
        python -m venv venv
        ./source/venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        deactivate
        
    - name: Run Unit Tests
      run: |
        python -m unittest discover
    - name: Configure Integration Tests for Linux
      if: ${{matrix.os}} == 'ubuntu-latest'
      run: |
        mv ./Acceptance/BookStore/Steps ./Acceptance/BookStore/steps
        ls -lhrt
        chmod +x startDjangoWithTestUser.py
        ls -lhrt startDjangoWithTestUser.py
        echo "alias python='python3'" >> ~/.bashrc
          
    - name: Run Integation Tests
      run: |
        behave ./Acceptance/BookStore/
