name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
          
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '3.10'
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Checkout React App
      uses: actions/checkout@v3
      with:
          repository: juandeaglio/TailwindCSS
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: TailwindCSS
    - name: setup node
      uses: actions/setup-node@v3

    - name: setup nginx
      run: |
        sudo apt-get install -y nginx
        
    - name: Install Windows Dependencies
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        dir
        dir ./TailwindCSS
        python -m venv venv
        ./venv/Scripts/activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd TailwindCSS
        npm install
        npm run build
        cd ..

    - name: Install Linux Dependencies
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        python -m venv venv
        source ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "alias python='python3'" >> ~/.bashrc
        #npm install --prefix ./TailwindCSS/
        #npm run build --prefix ./TailwindCSS/
        touch ./nginx.conf
        sudo usermod -a -G $(whoami) www-data
        sudo groups www-data
        sudo chown -R www-data:www-data ./static/
        sudo chmod 755 /var/lib/nginx/
        sudo chmod u+w ./static/
        sudo chmod u+w ./static/imgs/
        sudo chmod u+w ./static/imgs/*
        pwd
        sudo ln -s $(pwd)/nginx.conf /etc/nginx/sites-available/bookstore.conf
        sudo ln -s $(pwd)/nginx.conf /etc/nginx/sites-enabled/bookstore.conf
        ls-lhrt ./static/
        ls -lhrt ./static/imgs/
        
    - name: Run Window test Tests
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        ./venv/Scripts/activate.ps1
        python -m unittest discover

    - name: Run Linux test Tests
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        source ./venv/bin/activate
        python -m unittest discover -p "Test_*.py"
        ls -lhrt
        
    - name: Configure Integration Tests for Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        mv ./Acceptance/BookStore/Steps ./Acceptance/BookStore/steps
        ls -lhrt
        chmod +x startDjangoWithTestUser.py
        source ./venv/bin/activate
        behave ./Acceptance/BookStore/
        

    - name: Print nginx error log
      if: ${{always() && matrix.os == 'ubuntu-latest'}}
      run: |
          sudo cat /var/log/nginx/error.log
          
    - name: Run Windows Integation Tests
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        ./venv/Scripts/activate.ps1
        behave ./Acceptance/BookStore/
      
