name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, ]
          
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python '3.10'
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

        
    - name: Install Windows Dependencies
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        python -m venv venv
        ./venv/Scripts/activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Linux Dependencies
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        python -m venv venv
        source ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "alias python='python3'" >> ~/.bashrc
        
    - name: Run Window Unit Tests
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        ./venv/Scripts/activate.ps1
        python -m unittest discover

    - name: Run Linux Unit Tests
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        source ./venv/bin/activate
        python -m unittest discover
        
    - name: Configure Integration Tests for Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: |
        mv ./Acceptance/BookStore/Steps ./Acceptance/BookStore/steps
        ls -lhrt
        chmod +x startDjangoWithTestUser.py
        ls -lhrt startDjangoWithTestUser.py
        source ./venv/bin/activate
        behave ./Acceptance/BookStore/
          
    - name: Run Windows Integation Tests
      if: ${{matrix.os == 'windows-latest'}}
      run: |
        ./venv/Scripts/activate.ps1
        behave ./Acceptance/BookStore/
